---
name: Lint docs
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: "0 6 * * *"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs .
